version: "3"

services:
  app-cem:
    build: .
    container_name: go-app-cem304
    ports:
      - "9000:9000"
    volumes:
      - .:/go/src/

  db:
    image: postgres:15.1-alpine3.17
    container_name: go304-db-pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=cem304
    ports:
      - "5432:5432"
    volumes:
      - ./.pg-data:/var/lib/postgresql/data
      - ./postgres/tables.sql:/docker-entrypoint-initdb.d/init.sql
